#!/bin/bash

set -e
source settings
here=$(pwd)
name="$1"

if [ -z "$name" ]
then
  name="./res/res"
fi
echo "running simulation using name: $name."

rm -f "$name"*.obj

python main.py \
  --out "$name" \
  --procs 6 \
  --vnum 100000000 \
  --nearl 0.0028 \
  --farl 0.04 \
  --stp 1.0e-7 \
  --attract 0.9 \
  --reject 1.0 \
  --stat 100 \

